#!/bin/bash

# devcontainer features test -f rust-extra --remote-user vscode --skip-autogenerated --skip-duplicated .

# This test file will be executed against an auto-generated devcontainer.json that
# includes the 'hello' Feature with no options.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# Eg:
# {
#    "image": "<..some-base-image...>",
#    "features": {
#      "hello": {}
#    },
#    "remoteUser": "root"
# }
#
# Thus, the value of all options will fall back to the default value in
# the Feature's 'devcontainer-feature.json'.
# For the 'hello' feature, that means the default favorite greeting is 'hey'.
#
# These scripts are run as 'root' by default. Although that can be changed
# with the '--remote-user' flag.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#                   --features hello   \
#                   --remote-user root \
#                   --skip-scenarios   \
#                   --base-image mcr.microsoft.com/devcontainers/base:ubuntu \
#                   /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib. Syntax is...
# check <LABEL> <cmd> [args...]
check "execute command" bash -c "ls -l | grep 'hey, $(whoami)!'"
check "execute command" bash -c "ls -l"
check "execute command" bash -c "whoami"
# check "execute command" bash -c "cargo audit --version | grep 'cargo-audit-audit'"
# check "execute command" bash -c "cargo add --help | grep 'Add dependencies to a Cargo.toml manifest file'"
# check "execute command" bash -c "cargo expand --version | grep 'cargo-expand'"
# check "execute command" bash -c "cargo watch --version | grep 'cargo-watch'"

# check "check CARGO_HOME created directory permissions" bash -c "stat -c '%G:%a' ${CARGO_HOME}/binstall | grep 'rustlang:2775'"
# check "check CARGO_HOME created file permissions" bash -c "stat -c '%G:%a' ${CARGO_HOME}/bin/cargo-audit | grep 'rustlang:775'"

# check "check Cargo build artifacts directory does not exist" bash -c "! ls -l /usr/local/cargo | grep registry"
check "check if locale is installed" bash -c "which locale | grep 'locale'"
# check "check if locale is installed" bash -c "locale -a | grep 'en_US.utf8'"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
