name: Build and push Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push PHP 8.1 (PHP-FPM) image
        uses: docker/build-push-action@v2
        with:
          context: ./php8.1-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php8.1-fpm
            kodansha/bedrock:php8.1.9-fpm
            ghcr.io/kodansha/bedrock:php8.1-fpm
            ghcr.io/kodansha/bedrock:php8.1.9-fpm

      - name: Build and push PHP 8.0 (PHP-FPM) image
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php8.0-fpm
            kodansha/bedrock:php8.0.22-fpm
            ghcr.io/kodansha/bedrock:php8.0-fpm
            ghcr.io/kodansha/bedrock:php8.0.22-fpm

      - name: Build and push PHP 8.1 image
        uses: docker/build-push-action@v2
        with:
          context: ./php8.1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:latest
            kodansha/bedrock:php8.1
            kodansha/bedrock:php8.1.9
            ghcr.io/kodansha/bedrock:latest
            ghcr.io/kodansha/bedrock:php8.1
            ghcr.io/kodansha/bedrock:php8.1.9

      - name: Build and push PHP 8.0 image
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php8.0
            kodansha/bedrock:php8.0.22
            ghcr.io/kodansha/bedrock:php8.0
            ghcr.io/kodansha/bedrock:php8.0.22

      - name: Build and push PHP 7.4 image
        uses: docker/build-push-action@v2
        with:
          context: ./php7.4
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php7.4
            kodansha/bedrock:php7.4.28
            ghcr.io/kodansha/bedrock:php7.4
            ghcr.io/kodansha/bedrock:php7.4.28

      - name: Build and push PHP 7.3 image
        uses: docker/build-push-action@v2
        with:
          context: ./php7.3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php7.3
            kodansha/bedrock:php7.3.33
            ghcr.io/kodansha/bedrock:php7.3
            ghcr.io/kodansha/bedrock:php7.3.33
