name: PHP 7.3

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push PHP 7.3 image
        uses: docker/build-push-action@v3
        with:
          context: ./php7.3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kodansha/bedrock:php7.3
            kodansha/bedrock:php7.3.33
            ghcr.io/kodansha/bedrock:php7.3
            ghcr.io/kodansha/bedrock:php7.3.33
